### PR TITLE
Added pagination support to environments endpoint

### PR DESCRIPTION
**Pull request by nilver**
Fixes https://github.com/alerta/alerta/issues/1602

### CODE REVIEW

**Comment by nilver** [comment]
Hi @satterly , Can you take a look ? Please

**Comment by satterly** [comment]
Hi. Thanks for the PR. Can you add some tests?

**Comment by satterly** [comment]
Thanks! 👍

**Comment by satterly** [comment]
Had to revert this pull request because it broke the "environments" endpoint.

**Comment by nilver** [comment]
Hi,
 Could u share the error to fix it? 

Thanks.

**Pull request merged**
