### PR TITLE
Docker build with pyproject.toml

### PR DESCRIPTION
**Pull request by sixcare**
Related to https://github.com/alerta/alerta/pull/1797 fix docker builds to work with pyproject.toml

Co-authored-by: Sigurd Våg Aaknes <sigurdvaa@gmail.com>

### CODE REVIEW

**Comment by hyberdk** [comment]
so does this PR omit the #1797 PR? or how should it be understood?

**Comment by sixcare** [comment]
> so does this PR omit the #1797 PR? or how should it be understood?

No, I branched out of from the same branch as the one that I want to merge in https://github.com/alerta/alerta/pull/1797.

I shouldn have mentioned it in this PR or put it as draft until https://github.com/alerta/alerta/pull/1797 has been accepted

**Comment by satterly** [comment]
Hey, I've just noticed that in trying to get tests to pass on the master branch I've made several changes that you were planning to make here in this branch. Can you split out those changes that you would still like to make into much smaller changes and we can take them one by one? Thanks.

**Comment by sixcare** [comment]
pyproject.toml won't be implemnted at this time

**Pull request closed without merging**
