### PR TITLE
PingFederate users can use OpenID Connect auth

### PR DESCRIPTION
**Pull request by satterly**
Tidy-ups ...
 * remove PingFederate code (use OpenID instead)
 * rename `saml2` to `saml` to avoid confusion with pysaml2
 * remove unused imports

/cc @sushovan23 Any reason why PingFederate could not use generic OpenID Connect auth module?

### CODE REVIEW

**Comment by sushovan23** [comment]
should be able to. i will look into the config settings and check

**Comment by satterly** [comment]
Thanks a lot. I would have tested this myself but I've been trying for weeks to get a trial license out of Ping Identity and have given up. If there's some aspect missing let me know. Did the same for Azure the other day. See #997

**Comment by sushovan23** [comment]
@satterly Can I use my current client ID with openid/pingfederate or I need to create a new client ID for azure openid? 
I can only use openid/pingfederate right now

**Comment by satterly** [comment]
client id's are associated with a particular application for a particular authorization provider. You can only use one auth strategy at a time with Alerta. I was hoping you could test using the `openid` auth provider with your pingfederate environment and let me know if it works or not. Thanks.

**Comment by satterly** [comment]
@sushovan23 Have you had a chance to review this yet? I need to merge this so I can release some other changes as well. Thanks.

**Comment by sushovan23** [comment]
I can do today. what would be best way to test this? take changes manually and copy paste and test? or there is some standard way.

**Comment by sushovan23** [comment]
right now i follow :
/opt/alerta/bin/pip install alerta-server alerta
wget -q -O - https://github.com/alerta/alerta-webui/releases/latest/download/alerta-webui.tar.gz | tar zxf -

**Comment by satterly** [comment]
`pip install` won't work because it hasn't be released as a packaged version yet.

You don't actually have to change any code at all. You just need to change your config from using `AUTH_PROVIDER=pingfederate` to `AUTH_PROVIDER=openid` and use the generic "openid" config options.

**Comment by satterly** [comment]
For example, the google config changes like this ...
```
# Google
AUTH_PROVIDER='google'
OAUTH2_CLIENT_ID='736147134702-2lk9kqg6jueldtej10ajqo89jnbakr71.apps.googleusercontent.com'
OAUTH2_CLIENT_SECRET='secret'
```

```
# Google (using generic OpenID Connect options)
AUTH_PROVIDER='openid'
OIDC_ISSUER_URL = 'https://accounts.google.com'
OAUTH2_CLIENT_ID='736147134702-2lk9kqg6jueldtej10ajqo89jnbakr71.apps.googleusercontent.com'
OAUTH2_CLIENT_SECRET='secret'
```

You basically just need to set a valid `OIDC_ISSUER_URL` if the auth provider supports OpenID Connect -- which PingFederate say they do.

**Comment by sushovan23** [comment]
also can you send me the config.json? 
i have following:
```
{
        "endpoint": "/api",
        "provider": "pingfederate",
        "client_id": "xxx",
        "pingfederate_url": "https://xxxx",
        "dates": {
                "shortTime": "shortTime",
                "mediumDate": "medium",
                "longDate": "M/d/yyyy h:mm:ss:sss a (Z)"
        }
}
```

I suppose this will change to :
```
{
        "endpoint": "/api",
        "provider": "openid",
        "client_id": "xxx",
        "oidc_auth_url": "xxx",
        "dates": {
                "shortTime": "shortTime",
                "mediumDate": "medium",
                "longDate": "M/d/yyyy h:mm:ss:sss a (Z)"
        }
}
```
please confirm

**Comment by satterly** [comment]
The `config.json` is auto-generated from the server config. You need to work out what your Issuer URL is. I don't know what it is. It is unique for every environment.

**Comment by satterly** [comment]
I've just done some googling and this might work ...
```
OIDC_ISSUER_URL = 'https://pingfederate.example.com:9031'
```

Obviously, replace `pingfederate.example.com` with your PingFederate hostname.

**Comment by sushovan23** [comment]
also what is different between - OIDC_AUTH_URL and OIDC_ISSUER_URL ?

Something is missing in implementation from openid point of view.

There is authentication_url & token_url  from pingfederate point of view. 

in your configuration it only needs one url? Which one do i provide?

**Comment by sushovan23** [comment]
Its not working - 
```
OAUTH2_CLIENT_ID = 'xxxxx'
OAUTH2_CLIENT_SECRET  = 'xxxxx'
AUTH_PROVIDER = 'openid'
OIDC_ISSUER_URL  = 'auth_url'
```

config.json file which i created manually:
```
{
        "endpoint": "/api",
        "provider": "openid",
        "client_id": "xxxx",
        "oidc_auth_url": "auth_url",
        "dates": {
                "shortTime": "shortTime",
                "mediumDate": "medium",
                "longDate": "M/d/yyyy h:mm:ss:sss a (Z)"
        }
}
right now alerta is not starting up:
```
Jun 18 19:34:47 openstacklocal alertad[6765]:   File "/opt/alerta/lib64/python3.6/site-packages/alerta/auth/oidc.py", line 34, in get_oidc_configuration
Jun 18 19:34:47 openstacklocal alertad[6765]:     config = r.json()
Jun 18 19:34:47 openstacklocal alertad[6765]:   File "/opt/alerta/lib64/python3.6/site-packages/requests/models.py", line 897, in json
Jun 18 19:34:47 openstacklocal alertad[6765]:     return complexjson.loads(self.text, **kwargs)
Jun 18 19:34:47 openstacklocal alertad[6765]:   File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
Jun 18 19:34:47 openstacklocal alertad[6765]:     return _default_decoder.decode(s)
Jun 18 19:34:47 openstacklocal alertad[6765]:   File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
Jun 18 19:34:47 openstacklocal alertad[6765]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jun 18 19:34:47 openstacklocal alertad[6765]:   File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
Jun 18 19:34:47 openstacklocal alertad[6765]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Jun 18 19:34:47 openstacklocal alertad[6765]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Jun 18 19:34:47 openstacklocal alertad[6765]:
                                                                    During handling of the above exception, another exception occurred:
Jun 18 19:34:47 openstacklocal alertad[6765]: Traceback (most recent call last):
Jun 18 19:34:47 openstacklocal alertad[6765]:   File "wsgi.py", line 1, in <module>
Jun 18 19:34:47 openstacklocal alertad[6765]:     from alerta import app
Jun 18 19:34:47 openstacklocal alertad[6765]:   File "/opt/alerta/lib64/python3.6/site-packages/alerta/__init__.py", line 29, in <module>
Jun 18 19:34:47 openstacklocal alertad[6765]:     app = create_app()
Jun 18 19:34:47 openstacklocal alertad[6765]:   File "/opt/alerta/lib64/python3.6/site-packages/alerta/app.py", line 80, in create_app
Jun 18 19:34:47 openstacklocal alertad[6765]:     app.register_blueprint(auth_blueprint)
Jun 18 19:34:47 openstacklocal alertad[6765]:   File "/opt/alerta/lib64/python3.6/site-packages/flask/app.py", line 66, in wrapper_func
Jun 18 19:34:47 openstacklocal alertad[6765]:     return f(self, *args, **kwargs)
Jun 18 19:34:47 openstacklocal alertad[6765]:   File "/opt/alerta/lib64/python3.6/site-packages/flask/app.py", line 1115, in register_blueprint
Jun 18 19:34:47 openstacklocal alertad[6765]:     blueprint.register(self, options, first_registration)
Jun 18 19:34:47 openstacklocal alertad[6765]:   File "/opt/alerta/lib64/python3.6/site-packages/alerta/auth/__init__.py", line 10, in register
Jun 18 19:34:47 openstacklocal alertad[6765]:     oidc_config, _ = oidc.get_oidc_configuration(app)
Jun 18 19:34:47 openstacklocal alertad[6765]:   File "/opt/alerta/lib64/python3.6/site-packages/alerta/auth/oidc.py", line 36, in get_oidc_configuration
Jun 18 19:34:47 openstacklocal alertad[6765]:     raise ApiError('Could not get OpenID configuration from well known URL: {}'.format(str(e)), 503)
Jun 18 19:34:47 openstacklocal alertad[6765]: alerta.exceptions.ApiError: Could not get OpenID configuration from well known URL: Expecting value: line 1 column 1 (char 0)

**Comment by satterly** [comment]
You only need `OIDC_ISSUER_URL`. Alerta dynamically determines the `OIDC_AUTH_URL` which it passes to the web UI so it can initiate authentication.

Did you literally set `OIDC_ISSUER_URL` to the word "auth_url" or have you changed that to protect the actual hostname? Because "auth_url" is not a valid URL.

**Comment by sushovan23** [comment]
in anycase we would need to provide two urls - one for authorization which will be the auth_url and one to fetch the token and username from within the token so that would be the token_url. 
right now after we login to alerta using pingfederate we display the username and email address from the token which is received. 

I did set to the actual authorization url which is given to us. There is web security team which provides us with clientid. They provide us three urls to perform all application level code to implement oauth. 
auth url, token url and userinfo_url (userinfo_url i didn't use in pingfederate implementation)

**Comment by satterly** [comment]
Can we switch to Gitter? I need to explain OpenID Connect to you again.

**Comment by sushovan23** [comment]
thanks for the suggestion. it works i tested it out

**Pull request merged**
