### PR TITLE
Added Prometheus Metrics for Flask

### LINKED ISSUE #773: Exporting request statistics for Prometheus monitoring
**Is your feature request related to a problem? Please describe.**
No. This feature request is related to better monitoring of Alerta application itself in production environments. Alerta by default export certain parameters at `/management/metrics` but is limited to alerts count and status.

By adding more parameters like API hits count, status codes counter, etc Alerta's health can be monitored.

**Describe the solution you'd like**
I was looking into solutions and https://github.com/rycus86/prometheus_flask_exporter seems to do the job.

The diff looks like this:

```
--- a/alerta/app.py
+++ b/alerta/app.py
@@ -3,6 +3,7 @@ from typing import Any, Dict
 from flask import Flask
 from flask_compress import Compress
 from flask_cors import CORS
+from prometheus_flask_exporter import PrometheusMetrics
 from raven.contrib.flask import Sentry
 from werkzeug.contrib.fixers import ProxyFix
 
@@ -33,6 +34,7 @@ sentry = Sentry()
 mailer = Mailer()
 plugins = Plugins()
 custom_webhooks = CustomWebhooks()
+metrics = PrometheusMetrics(app=None)
 
 
 def create_app(config_override: Dict[str, Any]=None, environment: str=None) -> Flask:
@@ -56,6 +58,7 @@ def create_app(config_override: Dict[str, Any]=None, environment: str=None) -> F
     db.init_db(app)
     qb.init_app(app)
     sentry.init_app(app)
+    metrics.init_app(app)
 
     mailer.register(app)
     plugins.register(app)
```

The below metrics are then generated at `/metrics`

```
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 780812288.0
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 55132160.0
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1544079367.44
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 1.92
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 11.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="6",patchlevel="6",version="3.6.6"} 1.0
# HELP python_gc_collected_objects Objects collected during gc
# TYPE python_gc_collected_objects histogram
python_gc_collected_objects_bucket{generation="0",le="500.0"} 67.0
python_gc_collected_objects_bucket{generation="0",le="1000.0"} 92.0
python_gc_collected_objects_bucket{generation="0",le="5000.0"} 92.0
python_gc_collected_objects_bucket{generation="0",le="10000.0"} 92.0
python_gc_collected_objects_bucket{generation="0",le="50000.0"} 92.0
python_gc_collected_objects_bucket{generation="0",le="+Inf"} 92.0
python_gc_collected_objects_count{generation="0"} 92.0
python_gc_collected_objects_sum{generation="0"} 20965.0
python_gc_collected_objects_bucket{generation="1",le="500.0"} 5.0
python_gc_collected_objects_bucket{generation="1",le="1000.0"} 5.0
python_gc_collected_objects_bucket{generation="1",le="5000.0"} 8.0
python_gc_collected_objects_bucket{generation="1",le="10000.0"} 8.0
python_gc_collected_objects_bucket{generation="1",le="50000.0"} 8.0
python_gc_collected_objects_bucket{generation="1",le="+Inf"} 8.0
python_gc_collected_objects_count{generation="1"} 8.0
python_gc_collected_objects_sum{generation="1"} 4331.0
python_gc_collected_objects_bucket{generation="2",le="500.0"} 1.0
python_gc_collected_objects_bucket{generation="2",le="1000.0"} 1.0
python_gc_collected_objects_bucket{generation="2",le="5000.0"} 1.0
python_gc_collected_objects_bucket{generation="2",le="10000.0"} 1.0
python_gc_collected_objects_bucket{generation="2",le="50000.0"} 1.0
python_gc_collected_objects_bucket{generation="2",le="+Inf"} 1.0
python_gc_collected_objects_count{generation="2"} 1.0
python_gc_collected_objects_sum{generation="2"} 0.0
# TYPE python_gc_collected_objects_created gauge
python_gc_collected_objects_created{generation="0"} 1544079368.40282
python_gc_collected_objects_created{generation="1"} 1544079368.4353716
python_gc_collected_objects_created{generation="2"} 1544079368.5652938
# HELP python_gc_uncollectable_objects Uncollectable object found during GC
# TYPE python_gc_uncollectable_objects histogram
python_gc_uncollectable_objects_bucket{generation="0",le="500.0"} 92.0
python_gc_uncollectable_objects_bucket{generation="0",le="1000.0"} 92.0
python_gc_uncollectable_objects_bucket{generation="0",le="5000.0"} 92.0
python_gc_uncollectable_objects_bucket{generation="0",le="10000.0"} 92.0
python_gc_uncollectable_objects_bucket{generation="0",le="50000.0"} 92.0
python_gc_uncollectable_objects_bucket{generation="0",le="+Inf"} 92.0
python_gc_uncollectable_objects_count{generation="0"} 92.0
python_gc_uncollectable_objects_sum{generation="0"} 0.0
python_gc_uncollectable_objects_bucket{generation="1",le="500.0"} 8.0
python_gc_uncollectable_objects_bucket{generation="1",le="1000.0"} 8.0
python_gc_uncollectable_objects_bucket{generation="1",le="5000.0"} 8.0
python_gc_uncollectable_objects_bucket{generation="1",le="10000.0"} 8.0
python_gc_uncollectable_objects_bucket{generation="1",le="50000.0"} 8.0
python_gc_uncollectable_objects_bucket{generation="1",le="+Inf"} 8.0
python_gc_uncollectable_objects_count{generation="1"} 8.0
python_gc_uncollectable_objects_sum{generation="1"} 0.0
python_gc_uncollectable_objects_bucket{generation="2",le="500.0"} 1.0
python_gc_uncollectable_objects_bucket{generation="2",le="1000.0"} 1.0
python_gc_uncollectable_objects_bucket{generation="2",le="5000.0"} 1.0
python_gc_uncollectable_objects_bucket{generation="2",le="10000.0"} 1.0
python_gc_uncollectable_objects_bucket{generation="2",le="50000.0"} 1.0
python_gc_uncollectable_objects_bucket{generation="2",le="+Inf"} 1.0
python_gc_uncollectable_objects_count{generation="2"} 1.0
python_gc_uncollectable_objects_sum{generation="2"} 0.0
# TYPE python_gc_uncollectable_objects_created gauge
python_gc_uncollectable_objects_created{generation="0"} 1544079368.4029064
python_gc_uncollectable_objects_created{generation="1"} 1544079368.4354153
python_gc_uncollectable_objects_created{generation="2"} 1544079368.565342
# HELP python_gc_duration_seconds Time spent in garbage collection
# TYPE python_gc_duration_seconds histogram
python_gc_duration_seconds_bucket{generation="0",le="0.005"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="0.01"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="0.025"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="0.05"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="0.075"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="0.1"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="0.25"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="0.5"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="0.75"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="1.0"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="2.5"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="5.0"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="7.5"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="10.0"} 92.0
python_gc_duration_seconds_bucket{generation="0",le="+Inf"} 92.0
python_gc_duration_seconds_count{generation="0"} 92.0
python_gc_duration_seconds_sum{generation="0"} 0.014969587326049805
python_gc_duration_seconds_bucket{generation="1",le="0.005"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="0.01"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="0.025"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="0.05"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="0.075"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="0.1"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="0.25"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="0.5"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="0.75"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="1.0"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="2.5"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="5.0"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="7.5"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="10.0"} 8.0
python_gc_duration_seconds_bucket{generation="1",le="+Inf"} 8.0
python_gc_duration_seconds_count{generation="1"} 8.0
python_gc_duration_seconds_sum{generation="1"} 0.006600379943847656
python_gc_duration_seconds_bucket{generation="2",le="0.005"} 0.0
python_gc_duration_seconds_bucket{generation="2",le="0.01"} 0.0
python_gc_duration_seconds_bucket{generation="2",le="0.025"} 1.0
python_gc_duration_seconds_bucket{generation="2",le="0.05"} 1.0
python_gc_duration_seconds_bucket{generation="2",le="0.075"} 1.0
python_gc_duration_seconds_bucket{generation="2",le="0.1"} 1.0
python_gc_duration_seconds_bucket{generation="2",le="0.25"} 1.0
python_gc_duration_seconds_bucket{generation="2",le="0.5"} 1.0
python_gc_duration_seconds_bucket{generation="2",le="0.75"} 1.0
python_gc_duration_seconds_bucket{generation="2",le="1.0"} 1.0
python_gc_duration_seconds_bucket{generation="2",le="2.5"} 1.0
python_gc_duration_seconds_bucket{generation="2",le="5.0"} 1.0
python_gc_duration_seconds_bucket{generation="2",le="7.5"} 1.0
python_gc_duration_seconds_bucket{generation="2",le="10.0"} 1.0
python_gc_duration_seconds_bucket{generation="2",le="+Inf"} 1.0
python_gc_duration_seconds_count{generation="2"} 1.0
python_gc_duration_seconds_sum{generation="2"} 0.01081395149230957
# TYPE python_gc_duration_seconds_created gauge
python_gc_duration_seconds_created{generation="0"} 1544079368.4026442
python_gc_duration_seconds_created{generation="1"} 1544079368.4352732
python_gc_duration_seconds_created{generation="2"} 1544079368.5651913
# HELP alerta_http_request_duration_seconds Flask HTTP request duration in seconds
# TYPE alerta_http_request_duration_seconds histogram
alerta_http_request_duration_seconds_bucket{le="0.005",method="GET",path="/",status="200"} 0.0
alerta_http_request_duration_seconds_bucket{le="0.01",method="GET",path="/",status="200"} 0.0
alerta_http_request_duration_seconds_bucket{le="0.025",method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_bucket{le="0.05",method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_bucket{le="0.075",method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_bucket{le="0.1",method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_bucket{le="0.25",method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_bucket{le="0.5",method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_bucket{le="0.75",method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_bucket{le="1.0",method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_bucket{le="2.5",method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_bucket{le="5.0",method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_bucket{le="7.5",method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_bucket{le="10.0",method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_bucket{le="+Inf",method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_count{method="GET",path="/",status="200"} 2.0
alerta_http_request_duration_seconds_sum{method="GET",path="/",status="200"} 0.0250144531019032
alerta_http_request_duration_seconds_bucket{le="0.005",method="GET",path="/keys",status="200"} 1.0
alerta_http_request_duration_seconds_bucket{le="0.01",method="GET",path="/keys",status="200"} 2.0
alerta_http_request_duration_seconds_bucket{le="0.025",method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_bucket{le="0.05",method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_bucket{le="0.075",method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_bucket{le="0.1",method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_bucket{le="0.25",method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_bucket{le="0.5",method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_bucket{le="0.75",method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_bucket{le="1.0",method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_bucket{le="2.5",method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_bucket{le="5.0",method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_bucket{le="7.5",method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_bucket{le="10.0",method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_bucket{le="+Inf",method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_count{method="GET",path="/keys",status="200"} 3.0
alerta_http_request_duration_seconds_sum{method="GET",path="/keys",status="200"} 0.024681525072082877
# TYPE alerta_http_request_duration_seconds_created gauge
alerta_http_request_duration_seconds_created{method="GET",path="/",status="200"} 1544079369.2363045
alerta_http_request_duration_seconds_created{method="GET",path="/keys",status="200"} 1544079416.8949583
# HELP alerta_http_request_total Total number of HTTP requests
# TYPE alerta_http_request_total counter
alerta_http_request_total{method="GET",status="200"} 5.0
# TYPE alerta_http_request_created gauge
alerta_http_request_created{method="GET",status="200"} 1544079369.2364287
# HELP alerta_exporter_info Information about the Prometheus Flask exporter
# TYPE alerta_exporter_info gauge
alerta_exporter_info{version="0.4.0"} 1.0
```

I believe it to be a good addition, if yes, shall I raise PR for it for discussing code changes?

### PR DESCRIPTION
**Pull request by skbly7**
Closes #773

### CODE REVIEW

**Comment by satterly** [comment]
I can't get this to work. I get the following errors...
```
2018-12-10 17:32:44,525 - alerta.plugins[3784]: INFO - No plugin routing rules found. All plugins will be evaluated. [in /Users/nsatterl/Projects/alerta/alerta/utils/plugin.py:45]
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/Users/nsatterl/.virtualenvs/alerta/bin/alertad", line 11, in <module>
    load_entry_point('alerta-server', 'console_scripts', 'alertad')()
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/flask/cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/flask/cli.py", line 293, in __init__
    self._load_unlocked()
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/flask/cli.py", line 367, in load_app
    app = call_factory(self, self.create_app)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/flask/cli.py", line 114, in call_factory
    return app_factory(script_info)
  File "/Users/nsatterl/Projects/alerta/alerta/commands.py", line 15, in _create_app
    return create_app()
  File "/Users/nsatterl/Projects/alerta/alerta/app.py", line 61, in create_app
    metrics.init_app(app)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/prometheus_flask_exporter/__init__.py", line 138, in init_app
    self._defaults_prefix, app
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/prometheus_flask_exporter/__init__.py", line 251, in export_defaults
    **buckets_as_kwargs
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/prometheus_client/metrics.py", line 494, in __init__
    labelvalues=labelvalues,
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/prometheus_client/metrics.py", line 103, in __init__
    registry.register(self)
  File "/Users/nsatterl/.virtualenvs/alerta/lib/python3.6/site-packages/prometheus_client/registry.py", line 29, in register
    duplicates))
ValueError: Duplicated timeseries in CollectorRegistry: {'flask_http_request_duration_seconds_created', 'flask_http_request_duration_seconds_bucket', 'flask_http_request_duration_seconds_sum', 'flask_http_request_duration_seconds_count'}
```

**Comment by skbly7** [comment]
Hi, can you please share the command with which you ran developmental server? I will try the same on my side and update the PR accordingly.

**Comment by satterly** [comment]
Run ...
```
$ alertad run --port 8080 --with-thread
```
database backend is Postgres.

**Comment by satterly** [comment]
Closing this until it's corrected and ready to be merged.

**Pull request closed without merging**
