### PR TITLE
Added LDAP group support #749

### LINKED ISSUE #749: Adding support for LDAP groups in LDAP authentication
**Is your feature request related to a problem? Please describe.**
The universal method for getting groups a member is part of is done via LDAP. Right now, Alerta's LDAP authentication don't fetch those groups. These groups can be useful to automatically assign users as different customer.

**Describe the solution you'd like**
Appending groups a user is part of in [LDAP authentication](https://github.com/alerta/alerta/blob/master/alerta/auth/basic_ldap.py#L55).

This change might need adding a new settings variable `LDAP_GROUP_FILTER` or refactoring of `LDAP_DOMAINS` variable. Example group filter is `(&(memberUid=%s)(objectClass=group))`.

The final code will look something like this:

```
    groups = [user.domain]
    groups_filter = current_app.config['LDAP_DOMAINS_GROUP'][domain] % username
    resultID = ldap_connection.search(basedn, ldap.SCOPE_SUBTREE, groups_filter)
    resultTypes, results = ldap_connection.result(resultID)
    for result in results:
        groups.append(user.domain + ':' + result[1]['cn'][0].decode("utf-8"))

    customers = get_customers(user.email, groups=groups)
```
NOTE: To not break multi-tenancy `user.domain:` has been appended to group names. This is due to the fact that different clients/domains can have repetitive group names.

If the feature and solution looks good shall I raise a PR for the same?

### PR DESCRIPTION
**Pull request by skbly7**
Closes #749

Example configuration:

```
LDAP_URL = 'ldap://localhost:389' 
LDAP_DOMAINS = {
    'example.com': 'uid=%s,ou=People,dc=example,dc=com'
}
LDAP_DOMAINS_GROUP = {
    'example.com': '(&(memberUid=%s)(objectClass=groupOfUniqueNames))'
}
LDAP_DOMAINS_BASEDN = {
    'example.com': 'dc=example,dc=com'
}
```

### CODE REVIEW

**Comment by satterly** [comment]
@Anderen2 Any chance you could review and/or test this? Thanks.

**Comment by skbly7** [comment]
Our functionality will break upon using `userdn` instead of `username` because entries as saved as `member=skbly7` and so on.

Also, when I am rethinking both are valid use cases i.e. need of username, userdn and email (some setups use it). Probably I can edit my PR to get configuration like (and code change accordingly):

```
LDAP_DOMAINS_GROUP = { 
    'example.com': {
        'filter': '(&(member=%s)(objectClass=groupOfUniqueNames))',
        'field': 'userdn'
     }
}
```

This _may_ increase group config complexity but provide generic solution to all type of setups. Or we can use something like `{0}, {1}, {2}` to map the same (example how search guard do this, [here](https://docs.search-guard.com/latest/active-directory-ldap-authorisation#approach-1-querying-the-role-subtree)). Though I personally dislike `{0}, {1}, {2}` because you need to refer documentation every time at cost of beautiful config. 😛

Your suggestion?

**Comment by Anderen2** [comment]
Hmm, what about using string format with keyword arguments? 

```
LDAP_DOMAINS_GROUP = {
    'example.com': '(&(memberUid={username})(objectClass=groupOfUniqueNames))'
    #OR 
    'example.com': '(&(member={userdn})(objectClass=groupOfUniqueNames))'
}
```

**Comment by skbly7** [comment]
Ah, this looks good to me. 😃 
I will update PR then to support `username`, `userdn` and `email` for making implementation generic.

**Comment by Anderen2** [comment]
Fantastic, thanks a lot!

**Comment by skbly7** [comment]
Hi, the PR is now updated to work with group filter as:

```
LDAP_DOMAINS_GROUP = {
    'example.com': '(&(memberUid={username})(objectClass=groupOfUniqueNames))'
    #OR 
    'example.com': '(&(member={userdn})(objectClass=groupOfUniqueNames))'
    #OR 
    'example.com': '(&(member={email})(objectClass=groupOfUniqueNames))'
}
```

**Comment by satterly** [comment]
@Anderen2 Can you "+1" (thumbs up) this PR and I'll merge? Thanks.

**Comment by Anderen2** [comment]
Thumbs up all the way! :+1:

**Comment by satterly** [comment]
Thanks.

**Comment by satterly** [comment]
[LDAP logins should use LDAP database for groups](https://trello.com/c/ZhHpgGcr/398-ldap-logins-should-use-ldap-database-for-groups)

**Pull request merged**
