### PR TITLE
Add CLIPBOARD_TEMPLATE setting

### PR DESCRIPTION
**Pull request by emillen**
Only merge this if you decide to merge the PR in the frontend: https://github.com/alerta/alerta-webui/pull/555

**Description**
to allow for configuring this web console setting in the backend: https://github.com/alerta/alerta-webui/pull/555

**Changes**

- Add `CLIPBOARD_TEMPLATE` setting, which can be used to set a template used for formatting the AlertDetail copy-button

---

**Example:**

Provided following alert-json
```json
{
  "text": "this is a major alert",
  "environment": "prod"
}
```
and this template
```python
CLIPBOARD_TEMPLATE = """
[{{environment | upper}}] Alert!
{{text}}
"""
```
would put the following text in your clipboard
```
[PROD] Alert!
this is a major alert
```

### CODE REVIEW

**Review by kennhardy — APPROVED** [review]
Looks good. Approving together with https://github.com/alerta/alerta-webui/pull/555

**Review by kennhardy — APPROVED** [review]
LGTM

**Review by satterly — CHANGES_REQUESTED** [review]
Please add a test to ensure template config set in the configuration file appears correctly in the API endpoint used by the web UI.

Edit: I can't find a useful example of such a test that you could use as a template so I will write one and push to this branch.

**Comment by emillen** [comment]
Are you working on it? 

Would you be fine with something like this? 

```python
class ApiConfigResponseTestCase(unittest.TestCase):

    def setUp(self):
        test_config = {
            'CLIPBOARD_TEMPLATE': 'this is our template'
        }
        self.app = create_app(test_config)
        self.client = self.app.test_client()

    def test_response_(self):

        response = self.client.get('/config')
        data = json.loads(response.data.decode('utf-8'))
        self.assertEqual(data['clipboard_template'], 'this is our template')

```

**Comment by satterly** [comment]
Yes, that's it. We need to test that config set in the configuration file is correctly returned by the `/config` endpoint.

But the config needs to actually be an example template not just "this is our template". Can you create a test template that uses all the possible template special characters? It would also be a chance to show what it can be used for. People look at the tests when documentation is lacking.

**Comment by emillen** [comment]
I went ahead and added it to the existing `test_config.py`

I hope that will suffice!

**Review by satterly — APPROVED** [review]

**Comment by satterly** [comment]
:+1:

**Pull request merged**
